In [37]:
import pandas as pd

In [46]:
df = pd.read_parquet('./data/business.parquet')

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150346 entries, 0 to 150345
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   business_id   150346 non-null  object
 1   name          150346 non-null  object
 2   address       145219 non-null  object
 3   city          150346 non-null  object
 4   state         150343 non-null  object
 5   postal_code   150273 non-null  object
 6   latitude      150346 non-null  float64
 7   longitude     150346 non-null  float64
 8   stars         150346 non-null  float64
 9   review_count  150346 non-null  float64
 10  is_open       150346 non-null  int64
 11  attributes    136602 non-null  object
 12  categories    150243 non-null  object
 13  hours         127123 non-null  object
dtypes: float64(4), int64(1), object(9)
memory usage: 16.1+ MB

In [37]:
df.head()

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,None,93101,34.426679,-119.711197,5.0,7.0,0,{'ByAppointmentOnly': 'True'},"Doctors, Traditional Chinese Medicine, Naturop...",None
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,None,63123,38.551126,-90.335695,3.0,15.0,1,{'BusinessAcceptsCreditCards': 'True'},"Shipping Centers, Local Services, Notaries, Ma...","{'Monday': '0:0-0:0', 'Tuesday': '8:0-18:30', ..."
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,None,85711,32.223236,-110.880452,3.5,22.0,0,"{'BikeParking': 'True', 'BusinessAcceptsCredit...","Department Stores, Shopping, Fashion, Home & G...","{'Monday': '8:0-22:0', 'Tuesday': '8:0-22:0', ..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,CA,19107,39.955505,-75.155564,4.0,80.0,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,MO,18054,40.338183,-75.471659,4.5,13.0,1,"{'BusinessAcceptsCreditCards': 'True', 'Wheelc...","Brewpubs, Breweries, Food","{'Wednesday': '14:0-22:0', 'Thursday': '16:0-2..."

In [38]:
df['categories'].unique()

array(['Doctors, Traditional Chinese Medicine, Naturopathic/Holistic, Acupuncture, Health & Medical, Nutritionists',
       'Shipping Centers, Local Services, Notaries, Mailbox Centers, Printing Services',
       'Department Stores, Shopping, Fashion, Home & Garden, Electronics, Furniture Stores',
       ...,
       'Shopping, Jewelry, Piercing, Toy Stores, Beauty & Spas, Accessories, Fashion',
       'Fitness/Exercise Equipment, Eyewear & Opticians, Shopping, Sporting Goods, Bikes',
       'Beauty & Spas, Permanent Makeup, Piercing, Tattoo'], dtype=object)

In [47]:
filtro_restaurantes = df['categories'].str.contains('restaurant', case=False, na=False)
filtro_hoteles = df['categories'].str.contains('Hotels', case=False, na=False)

df_result = df[filtro_restaurantes | filtro_hoteles].copy()

In [52]:
df_result.sample(5)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
95099,V_N2ZVEKMDIbUvATk50UlA,Copper Moon Coffee,550 University Blvd,Indianapolis,PA,46202,39.775584,-86.176043,2.0,9.0,1,"{'OutdoorSeating': 'False', 'RestaurantsGoodFo...","Bakeries, Coffee & Tea, Food, Sandwiches, Rest...",None
128811,5XLEKq639yBqDbZ3K1kRtQ,Charlie's Famous Hoagies,106 Whitehorse Rd,Voorhees Township,TN,8043,39.840804,-74.996758,3.5,7.0,0,"{'RestaurantsAttire': ""'casual'"", 'Restaurants...","Sandwiches, Restaurants","{'Monday': '11:0-21:0', 'Tuesday': '11:0-21:0'..."
132540,iku8LeNeBf0P3TOGiQOJbQ,Bob & Daughter Market,514 Park St,Clearwater,PA,33755,27.964893,-82.799324,4.0,9.0,0,"{'RestaurantsPriceRange2': '1', 'BusinessAccep...","Restaurants, Delis, Specialty Food, Fruits & V...","{'Monday': '7:0-16:0', 'Tuesday': '7:0-16:0', ..."
114008,Fz4mzQjAxyrN6tQLcZ73Bw,Not Your Average Joe's,561 Glen Eagle Square,Glen Mills,CA,19342,39.866261,-75.542808,3.5,317.0,1,"{'DriveThru': 'False', 'RestaurantsAttire': ""'...","Restaurants, Food, Burgers, American (New), Sa...","{'Monday': '11:30-21:0', 'Tuesday': '11:30-21:..."
115776,JIvfg4W979rqqfGDRD4MXA,Café Rue 52,503 S 52nd St,Philadelphia,NV,19143,39.951814,-75.226330,4.0,18.0,0,"{'HasTV': 'True', 'NoiseLevel': ""u'quiet'"", 'R...","Creperies, Coffee & Tea, Food, Desserts, Resta...","{'Monday': '6:30-18:0', 'Tuesday': '6:30-18:0'..."

In [54]:
df_result.info()

<class 'pandas.core.frame.DataFrame'>
Index: 57722 entries, 3 to 150340
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   business_id   57722 non-null  object
 1   name          57722 non-null  object
 2   address       56953 non-null  object
 3   city          57722 non-null  object
 4   state         57722 non-null  object
 5   postal_code   57698 non-null  object
 6   latitude      57722 non-null  float64
 7   longitude     57722 non-null  float64
 8   stars         57722 non-null  float64
 9   review_count  57722 non-null  float64
 10  is_open       57722 non-null  int64
 11  attributes    55597 non-null  object
 12  categories    57722 non-null  object
 13  hours         49246 non-null  object
dtypes: float64(4), int64(1), object(9)
memory usage: 6.6+ MB

In [53]:
# df_result.to_parquet('Busisness.parquet',index=False)